# include: package:flutter_lints/flutter.yaml

# linter:
#   rules:
#     avoid_print: true
#     prefer_single_quotes: true
#     always_use_package_imports: true
#     empty_statements: true
#     always_declare_return_types: true
#     camel_case_extensions: true
#     require_trailing_commas: true

include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
analyzer:
  exclude:
    - lib/firebase_options_dev.dart
    - lib/firebase_options_prod.dart
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
