name: drawing_board
description: "A new Flutter package project."
version: 0.54.0
homepage:

publish_to: none

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  drawly_core:
    path: ../drawly_core
  drawly_design_system:
    path: ../drawly_design_system
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_svg: ^2.0.9
  universal_platform: ^1.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
